about/urls.py
from django.urls import path
from .views import default_unit, all_motions, motion, unit, policy

urlpatterns = [
    path('', default_unit, name="clp"),
    path('policy/', policy, name="policy"),
    path('motions/', all_motions, name="motions"),
    path('motions/page:<page_no>', all_motions, name="motions_page"),
    path('motions/<motion_id>', motion, name="motion"),
    path('<unit_type>/<unit_slug>', unit, name="unit"),
]

meetings/urls.py
from django.urls import path
from .views import meeting, motion, all_meetings, meeting_minutes

urlpatterns = [
    path('', all_meetings, name="meetings"),
    path('page:<int:page>', all_meetings, name="meetings_page"),
    path('<slug:unit>/<int:year>-<int:month>-<int:day>', meeting, name="meeting"),

    path('<slug:unit>/<int:year>-<int:month>-<int:day>/agenda', meeting, name="agenda"),
    path('<slug:unit>/<int:year>-<int:month>-<int:day>/minutes', meeting_minutes, name="minutes"),

    path('<slug:unit>/<int:year>-<int:month>-<int:day>/motion/<int:motion>', motion, name="meeting_motion"),
]

about/models.py
from django.db import models
from django.apps import apps
from django.core.exceptions import ObjectDoesNotExist
import markdown2
import datetime
import calendar

class Policy(models.Model):
    headline = models.CharField(max_length=250)
    description = models.TextField()
    icon_class = models.CharField(max_length=25)
    color = models.CharField(max_length=25, null=True, blank=True, help_text="You can use any valid html color value.")

    def __str__(self):
        return self.headline

    def html(self):
        return markdown2.markdown(self.description)

    class Meta:
        verbose_name_plural = "policies"

class Person(models.Model):
    name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='uploads/avatars/', null=True, blank=True)
    email = models.CharField(max_length=1024, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "people"

class Unit(models.Model):
    TYPES = (
        ("CLP", "Constituency Labour Party"),
        ("BLP", "Branch Labour Party"),
        ("LCF", "Local Campaign Forum"),
        ("Group", "Labour Group"),
        ("Committee", "Committee"),
    )
    MEMBERSHIPS = (
        ("AM", "All members in the constituency"),
        ("BM", "All members in branch"),
        ("EM", "Elected members only")
    )
    DAYS = (
        (1, "Monday"),
        (2, "Tuesday"),
        (3, "Wednesday"),
        (4, "Thursday"),
        (5, "Friday"),
        (6, "Saturday"),
        (7, "Sunday")
    )
    name = models.CharField(max_length=250)
    slug = models.SlugField(unique=True, null=True)
    type = models.CharField(max_length=10, choices=TYPES)
    description = models.TextField()
    membership = models.CharField(max_length=3, choices=MEMBERSHIPS)
    members = models.ManyToManyField(Person, related_name='committees', through='Role')
    week_of_month = models.IntegerField(null=True)
    day_of_week = models.IntegerField(null=True, choices=DAYS)
    default_unit = models.BooleanField(default=False)

    class Meta:
        ordering = ['-default_unit', 'type']

    def __str__(self):
        return '%s %s' % (self.name, self.type)

    def nextMeeting(self):
        today = datetime.date.today()
        this_month_date = self.dateInMonth(year=today.year, month=today.month)

        if this_month_date < today:
            next_month = today + datetime.timedelta(days=32)
            return self.dateInMonth(year=next_month.year, month=next_month.month)

        return this_month_date

    def is_next_meeting_in_calendar(self):
        try:
            Meeting = apps.get_model('meetings', 'Meeting')
            Meeting.objects.get(unit=self, date=self.nextMeeting())
            return True
        except ObjectDoesNotExist:
            return False
    
    def dateInMonth(self, month, year):
        month_range = calendar.monthcalendar(year, month)
        week = self.week_of_month - 1
        day_of_week = self.day_of_week - 1
        first_week = month_range[0]
        first_week_day = first_week[day_of_week]

        if first_week_day == 0:
            week += 1

        while week > len(month_range) - 1:
            week -= 1

        date = month_range[week][day_of_week]

        while date == 0:
            week -= 1
            date = month_range[week][day_of_week]

        full_date = datetime.date(year, month, date)

        return full_date

class Role(models.Model):
    TITLES = (
        (1, "Chair"),
        (2, "Vice Chair"),
        (3, "Secretary"),
        (4, "Treasurer"),
        (5, "Vice Chair Membership"),
        (6, "Woman's Officer"),
        (7, "Policy Officer"),
        (8, "BAME Officer"),
        (9, "Disability Officer"),
        (10, "LGBT+ Officer"),
        (11, "Youth Officer"),
        (12, "Trade Union Liaison Officer"),
        (13, "Political Education Officer"),
        (14, "Communications and Social Media Officer"),
        (15, "Campaign Coordinator"),
        (16, "Procedures Secretary"),
        (17, "Selection Coordinator"),
        (21, "Member of Parliament"),
        (22, "Police & Crime Commissioner"),
        (31, "Group Leader"),
        (32, "Cabinet Member"),
        (33, "County Councillor"),
        (34, "City Councillor"),
        (35, "District Councillor"),
        (36, "Parish Councillor"),
        (50, "Delegate"),
        (51, "Observer"),
        (60, "Member"),
    )
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, null=True)
    term_ends_on = models.DateField()
    title = models.IntegerField(choices=TITLES)
    sub_title = models.CharField(max_length=200, null=True, blank=True, help_text="Authority/Ward name, or position title (i.e. for cabinet member,'Children's Services').")
    hide = models.BooleanField(default=False)

    class Meta:
        ordering = ['title', '-term_ends_on']

    def __str__(self):
        unit = self.unit
        if unit == None:
            unit = 'Constituency'

        return '%s, %s' % (self.title, unit)

class Motion(models.Model):
    STATUSES = (
        (" ", "Received"),
        ("R", "Rejected"),
        ("A", "Awaiting debate"),
        ("P", "Passed"),
        ("L", "Lost"),
        ("W", "Withdrawn"),
    )
    REJECTION_REASONS = (
        (
            "it is not clear what the motion is asking for.",
            "Unclear"
        ),
        (
            "the motion is against Labour Party rules or is otherwise out of order.",
            "Out of order"
        ),
        (
            "the motion is not directed towards a valid recipient.",
            "Invalid/No Recipient"
        ),
        (
            "a similar motion has recently been heard, is already scheduled, or this is otherwise a duplicate of an identical motion already dealt with.",
            "Duplicate"
        ),
        (
            "the motion is not directed towards a valid recipient.",
            "Invalid/No Recipient"
        ),
        (
            "this motion is vexatious; it has been submitted to frustrate the meeting or is not a serious motion.",
            "Vexatious"
        ),
    )
    title = models.CharField(max_length=1024)
    text = models.TextField()
    submitted_on = models.DateField()
    submitted_to = models.ForeignKey(Unit, on_delete=models.CASCADE)
    submitted_by = models.CharField(max_length=200)
    submitted_by_email = models.EmailField(blank=True, null=True)
    meeting = models.ForeignKey('meetings.Meeting', on_delete=models.SET_NULL, null=True, blank=True)
    debated_on = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=1, choices=STATUSES, default=" ")
    rejected_reason = models.CharField(max_length=1250, null=True, blank=True, choices=REJECTION_REASONS)

    def __str__(self):
        return self.title

    def html(self):
        return markdown2.markdown(self.text)

    def scheduled_for(self):
        if self.meeting:
            return self.meeting.date

        return None

    def status_icon(self):
        STATUS_ICONS = {
            " ": "check",
            "R": "times",
            "A": "hourglass",
            "P": "thumbs-up",
            "L": "thumbs-down",
            "W": "minus",
        }

        return 'fas fa-%s' % (STATUS_ICONS[self.status],)

    def status_text(self):
        STATUS_MESSAGES = {
            " ": "This motion was received on %s and is awaiting approval." % (format_date(self.submitted_on),),
            "R": "This motion was rejected by %s because %s" % (self.submitted_to, self.rejected_reason),
            "A": "This motion will be debated on %s by %s" % (format_date(self.scheduled_for()), self.submitted_to),
            "P": "This motion was debated by %s on %s and was agreed." % (self.submitted_to, format_date(self.debated_on)),
            "L": "This motion was debated by %s on %s but not agreed." % (self.submitted_to, format_date(self.debated_on)),
            "W": "This motion was withdrawn by its author.",
        }

        return STATUS_MESSAGES[self.status]

    def get_date(self):
        if self.status == ' ' or self.status == 'R' or self.status == 'W' or self.meeting is None:
            return format_date(self.submitted_on, False)

        if self.meeting:
            return format_date(self.scheduled_for(), False)

        return format_date(self.debated_on, False)

    class Meta:
        ordering = ['-meeting__date', 'submitted_on']

def format_date(date, long=True):
    if date is not None:
        if long:
            return date.strftime("%A, %-d %b %Y")

        return date.strftime("%B %Y")


    return date

blog/models.py
from django.db import models
import markdown2

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"

class Post(models.Model):
    STATUSES = (
        (" ", "Published"),
        ("D", "Draft"),
        ("A", "Archived")
    )

    headline = models.CharField(max_length=500)
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUSES)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="posts")
    text = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='uploads/%Y/%m/', null=True, blank=True)

    def __str__(self):
        return self.headline

    def html(self):
        return markdown2.markdown(self.text)

    def description(self, length=250):
        if len(self.text) < length:
            return self.text

        html = markdown2.markdown(self.text[:length-3] + '...')

        return html

meetings/models.py
from django.db import models
import datetime
import markdown2
from about.models import Unit, Motion


class Meeting(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name="meetings")
    date = models.DateField()
    time = models.TimeField()
    address = models.CharField(max_length=1200)
    notes = models.TextField(null=True, blank=True, help_text="This will be small print on the agenda. Use it for parking instructions etc.")
    attendees = models.TextField(null=True, blank=True,
                                   help_text="For the minutes, write a comma separated list of names of people who attended.")
    apologies = models.TextField(null=True, blank=True,
                                 help_text="For the minutes, write a comma separated list of names of people who attended.")

    def __str__(self):
        return '%s - %s' % (self.unit.name, self.get_date())

    def in_future(self):
        today = datetime.date.today()
        return self.date >= today

    def get_agenda_items(self):
        return AgendaItem.objects.filter(meeting=self)

    def count_agenda_items(self):
        return len(self.get_agenda_items())

    def get_motion_item(self):
        return self.count_agenda_items() + 1

    def get_motions(self):
        motions = Motion.objects.filter(meeting=self).exclude(status__in=[
            ' ', 'W', 'R'
        ])

        return motions

    def get_attachments(self):
        return Attachment.objects.filter(meeting=self)

    def get_date(self):
        return self.date.strftime("%b %Y")

    class Meta:
        unique_together = ['unit', 'date']
        ordering = [
            '-date',
            '-time'
        ]

class AgendaItem(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE, related_name="agenda_items")
    title = models.CharField(max_length=300)
    description = models.TextField(max_length=1500, null=True, blank=True,
                                   help_text="Add an explanation for the agenda.")

    minutes_notes = models.TextField(null=True, blank=True,
                                     help_text="Add the minutes notes for this item")

    order = models.IntegerField()

    def __str__(self):
        return '%s. %s' % (self.get_item_number(), self.title)

    def get_item_number(self):
        previous_items = AgendaItem.objects.filter(meeting=self.meeting, order__lt=self.order)
        return previous_items.count() + 1

    def get_minutes_notes_html(self):
        return markdown2.markdown(self.minutes_notes)

    def get_description_html(self):
        return markdown2.markdown(self.description)

    class Meta:
        ordering = [
            '-meeting__date',
            'order'
        ]

class Attachment(models.Model):
    title = models.CharField(max_length=200)
    file = models.FileField(upload_to='uploads/%Y/%m/')
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

meetings/views.py
from django.shortcuts import render, get_object_or_404
import datetime
from django.core.paginator import Paginator
from .models import Meeting
from about.models import Unit, Motion

def all_meetings(request, page_no=1):
    meetings = Meeting.objects.all()

    p = Paginator(meetings, 20)

    return render(request, 'pages/meetings.html', {
        "page": {
            "title": "Meetings",
            "description": "A list of meetings taking place in our CLP.",
        },
        "meetings": p.page(page_no),
        "p": p
    })

def meeting(request, unit, year, month, day):
    date = datetime.date(year=year, month=month, day=day)
    unit_obj = get_object_or_404(Unit, slug=unit)
    meeting = get_object_or_404(Meeting, unit=unit_obj, date=date)

    return render(request, 'pages/meeting.html', {
        "page": {
            "title": meeting,
            "description": "Information about %s" % (meeting,),
            "type": "agenda",
        },
        "meeting": meeting
    })



def meeting_minutes(request, unit, year, month, day):
    date = datetime.date(year=year, month=month, day=day)
    unit_obj = get_object_or_404(Unit, slug=unit)
    meeting = get_object_or_404(Meeting, unit=unit_obj, date=date)

    return render(request, 'pages/meeting.html', {
        "page": {
            "title": meeting,
            "description": "Information about %s" % (meeting,),
            "type": "minutes",
        },
        "meeting": meeting
    })


def motion(request, unit, year, month, day, motion):
    date = datetime.date(year=year, month=month, day=day)
    unit_obj = get_object_or_404(Unit, slug=unit)
    meeting = get_object_or_404(Meeting, unit=unit_obj, date=date)

    motion = get_object_or_404(Motion, pk=motion)

    return render(request, 'pages/motion.html', {
        "motion": motion,
        "meeting": meeting,
        "page": {
            "title": 'Motion - %s' % motion.title,
            "previous": "meeting",
            "description": "Text of a motion put to a meeting: %s" % (meeting,),
        }
    })

templates/pages/landing.html
{% extends 'template.html' %}

{%  block content %}

    {% include 'sections/information.html' %}
    {% include 'sections/latest-news.html' %}

{% endblock %}

templates/pages/meeting.html
{% extends 'template.html' %}
{% block content %}

    <section class="section cream">
        <header class="content post-header">
            <p class="title">Meeting</p>
            <h1 class="post-title">
                {{ meeting.unit }}
            </h1>
        </header>
        <header class="content subheader">
            <h2>Meeting details</h2>
            <h2>{{ meeting.get_date }}</h2>
        </header>
        <nav class="content tabs">
            <a href="{% url 'agenda' unit=meeting.unit.slug year=meeting.date.year month=meeting.date.month day=meeting.date.day %}"
               class="tab {% if page.type == 'agenda' %}active{% endif %}">
                Agenda
            </a>
            <a href="{% url 'minutes' unit=meeting.unit.slug year=meeting.date.year month=meeting.date.month day=meeting.date.day %}"
               class="tab {% if page.type == 'minutes' %}active{% endif %}">
                Minutes
            </a>
        </nav>
    </section>

    <section class="section">
        <dl class="content flex">
            <dt>Date</dt>
            <dd>{{ meeting.date }}</dd>
            <dt>Address</dt>
            <dd>{{ meeting.address }}</dd>
            {% if page.type == 'minutes' %}
                <dt>Attendees</dt>
                <dd>{{ meeting.attendees }}</dd>
                <dt>Apologies</dt>
                <dd>{{ meeting.apologies }}</dd>
            {% endif %}
            {% if meeting.get_attachments %}
                <dt>Attachments</dt>
                <dd>
                {% for a in meeting.get_attachments %}
                    <a href="{{ a.file.url }}" target="_blank">
                        {{ a.title }}
                    </a>{% if not forloop.last %},&nbsp;{% endif %}
                {% endfor %}
                </dd>
            {% endif %}
        </dl>

        {% if page.type == 'agenda' %}
            {% include 'tabs/agenda.html' %}
        {% endif %}

        {% if page.type == 'minutes' %}
            {% include 'tabs/minutes.html' %}
        {% endif %}

    </section>


{% if meeting.notes and page.type == 'agenda' %}
    <section class="section">
        <footer class="content subheader">
            <p class="text">
                {{ meeting.notes }}
            </p>
        </footer>
    </section>
{% endif %}

{% endblock %}

templates/pages/meetings.html
{% extends 'template.html' %}
{% block content %}
    <section class="section cream">
        <header class="content post-header">
            <p class="title">Meetings</p>
            <h1 class="post-title">
                All Meetings
            </h1>
        </header>
    </section>

    <section class="section">
        <article class="content">
            <table class="table">
                <tbody>
                {% for meeting in meetings %}
                    <tr>
                        <td>
                            {{ meeting }}
                        </td>
                        <td>
                            {% if meeting.in_future %}
                                <a href="{% url 'agenda' unit=meeting.unit.slug year=meeting.date.year month=meeting.date.month day=meeting.date.day %}">
                                    Agenda
                                </a>
                            {% else %}
                                <a href="{% url 'minutes' unit=meeting.unit.slug year=meeting.date.year month=meeting.date.month day=meeting.date.day %}">
                                    Minutes
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </article>
    </section>
    <section class="section cream">
        <article class="content paginator">
            {% if meetings.has_previous %}
                <a href="{% url 'meetings_page' page=meetings.previous_page_number %}" class="button red no-margin">
                    Previous
                </a>
            {% endif %}
            <div>
                {{ meetings.end_index }} of {{ p.count }}
            </div>
            {% if meetings.has_next %}
                <a href="{% url 'meetings_page' page=meetings.next_page_number %}" class="button red no-margin">
                    Next
                </a>
            {% endif %}
        </article>
    </section>
{% endblock %}

templates/pages/motion.html
{% extends 'template.html' %}
{% load static %}

{% block htmlhead %}
    <link rel="stylesheet" href="{% static 'motions.css' %}">
{% endblock %}

{% block content %}

    <section class="section cream">
        <header class="content post-header">
            <p class="title">Motion</p>
            <h1 class="post-title">
                {{ motion.title }}
            </h1>
        </header>
        <header class="content subheader">
            <h2>{{ motion.submitted_to }}</h2>
            <h2>{{ motion.get_date }}</h2>
        </header>
    </section>

    <section class="section no-bottom-padding">
        <article class="content status-banner">
            <i class="{{ motion.status_icon }}"></i>
            <div>
                <p>{{ motion.status_text }}</p>
            </div>
        </article>
    </section>

    <section class="section">
        <dl class="content flex">
            <dt>
                Written by
            </dt>
            <dd>
                {{ motion.submitted_by }}
            </dd>
            <dt>
                Status
            </dt>
            <dd>
                {{ motion.get_status_display }}
            </dd>
            {% if motion.status == 'A' %}
                <dt>
                    Scheduled for
                </dt>
                <dd>
                    {{ motion.scheduled_for }}
                </dd>
            {% endif %}
            <dt>
                Full text
            </dt>
            <dd>
                {{ motion.html|safe }}
            </dd>
        </dl>
    </section>

    <section class="section cream">
        <footer class="content">
            {% if page.previous == 'motions' %}
                <a href="{% url 'motions' %}" class="fancy-link blue" style="display: inline-block">
                    <i class="fas fa-arrow-left"></i>
                    Back to list of motions
                </a>
            {% endif %}

            {% if page.previous == 'meeting' %}
                <a href="{% url 'meeting' unit=meeting.unit.slug year=meeting.date.year month=meeting.date.month day=meeting.date.day %}" class="fancy-link blue" style="display: inline-block">
                    <i class="fas fa-arrow-left"></i>
                    Back to meeting agenda
                </a>
            {% endif %}
        </footer>
    </section>

{% endblock %}

templates/pages/motions.html
{% extends 'template.html' %}
{% block content %}
    <section class="section cream">
        <header class="content post-header">
            <p class="title">Motions</p>
            <h1 class="post-title">
                All Motions
            </h1>
            <p class="text">
                Motions are written proposals brought forward for debate at a meeting.
                You can see a list of motions submitted to this CLP or its committees and branches on this page.
            </p>
        </header>
    </section>

    <section class="section">
        <article class="content">
            <table class="table">

                <thead>
                <tr>
                    <th>
                        Title
                    </th>
                    <th>
                        Submitted To
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Date
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for motion in motions %}
                    <tr>
                        <td>
                            <a href="{% url 'motion' motion_id=motion.id %}">
                                {{ motion.title }}
                            </a>
                        </td>
                        <td>
                            {{ motion.submitted_to }}
                        </td>
                        <td>
                            {{ motion.get_status_display }}
                        </td>
                        <td>
                            {{ motion.get_date }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </article>
    </section>

    <section class="section cream">
        <article class="content paginator">
            {% if motions.has_previous %}
                <a href="{% url 'motions_page' page_no=motions.previous_page_number %}" class="button red no-margin">
                    Previous
                </a>
            {% endif %}
            <div>
                {{ motions.end_index }} of {{ p.count }}
            </div>
            {% if motions.has_next %}
                <a href="{% url 'motions_page' page_no=motions.next_page_number %}" class="button red no-margin">
                    Next
                </a>
            {% endif %}
        </article>
    </section>
{% endblock %}

templates/pages/unit.html
{% extends 'template.html' %}
{% load static %}

{% block htmlhead %}
    <link rel="stylesheet" href="{% static 'unit.css' %}">
{% endblock %}

{% block content %}

    <section class="section cream">
        <header class="content post-header">
            <p class="title">{{ unit.get_type_display }}</p>
            <h1 class="post-title">
                {{ unit }}
            </h1>
        </header>
    </section>

    <section class="section no-bottom-padding">
        <article class="content status-banner">
            <i class="far fa-calendar-check"></i>
            <div>
                <p>The next meeting will be held on</p>
                <p>
                    {{ unit.nextMeeting|date:'l' }}
                    the
                    <strong>
                        {{ unit.nextMeeting|date:'j' }}<sup>{{ unit.nextMeeting|date:'S' }}</sup>
                        of
                        {{ unit.nextMeeting|date:'F Y' }}
                    </strong>
                </p>
            </div>
        </article>
        {% if unit.is_next_meeting_in_calendar %}
            <article class="content paginator">
                        <span id="empty">
                        </span>
                <a class="fancy-link blue" href="{% url 'meeting' unit=unit.slug year=unit.nextMeeting.year month=unit.nextMeeting.month day=unit.nextMeeting.day %}">
                    View the agenda for this meeting
                    <i class="fas fa-arrow-right"></i>
                </a>
            </article>
        {% endif %}
        <article class="content">
            <p class="text">
                {{ unit.description }}
            </p>
        </article>
    </section>

    {% if unit.default_unit %}
        <section class="section">
            <header class="content">
                <h2 class="title">Branches & Committees</h2>
            </header>
            <section class="content-grid">
                {% for branch in branches %}
                    <a href="{% url 'unit' unit_type=branch.type unit_slug=branch.slug %}" class="block-button">
                        <h4>{{ branch }}</h4>
                        <p>{{ branch.description }}</p>
                        <footer class="meta">
                            <span class="fancy-link blue">
                                More about this {{ branch.get_type_display }}
                            <i class="fas fa-arrow-right"></i>
                            </span>
                        </footer>
                    </a>
                {% endfor %}
            </section>
        </section>
    {% endif %}

    <section class="section no-bottom-padding">
        {% if roles %}
            <header class="content">
                <h2 class="title">Officers</h2>
                <p>Members elected by other members to run the {{ unit.type }} day to day.</p>
            </header>
            <section class="content-block-grid people">
                {% for role in roles %}
                    {% include 'blocks/person.html' %}
                {% endfor %}
            </section>
        {% endif %}
    </section>

    {% if elected %}
        <section class="section no-bottom-padding">
            <header class="content">
                <h2 class="title">Representatives</h2>
                <p>Members who've been elected to public office.</p>
            </header>
            <section class="content-block-grid people">
                {% for role in elected %}
                    {% include 'blocks/person.html' %}
                {% endfor %}
            </section>
        </section>
    {% endif %}
    {% if members %}
        <section class="section">
            <header class="content">
                <h2 class="title">Members</h2>
                <p>Delegates and observers</p>
            </header>
            <section class="content-block-grid people">
                {% for role in members %}
                    {% include 'blocks/person.html' %}
                {% endfor %}
            </section>
        </section>
    {% endif %}

    <section class="section cream">
        <article class="content-grid">
            <a href="{% url 'policy' %}" class="info-link">
                <div class="icon-background">
                    <i class="fas fa-flag"></i>
                </div>
                <div>
                    <h4 class="icon-title">
                        Policies
                    </h4>
                    <p>
                        Find out about our values, policies, and what we would do for your area if we're
                        elected.
                    </p>
                    <footer>
                        <span class="fancy-link blue">Read our policies<i class="fas fa-arrow-right space"></i> </span>
                    </footer>
                </div>
            </a>
            <a href="{% url 'motions' %}" class="info-link">
                <div class="icon-background">
                    <i class="fas fa-scroll"></i>
                </div>
                <div>
                    <h4 class="icon-title">
                        Motions
                    </h4>
                    <p>
                        See a details of all motions submitted in this constituency,
                        or submit your own motion for debate at one of our committees or branches.
                    </p>
                    <footer>
                        <span class="fancy-link blue">See motions<i class="fas fa-arrow-right space"></i> </span>
                    </footer>
                </div>
            </a>
        </article>
    </section>
{% endblock %}